
  - 現在の研究室のGPU使用状況は，
    「onsei_check_gpus」というコマンドで確認できます。
  - 自分が確保したいGPUの枚数は，
    「onsei_register_desired_gpus」というコマンドで登録できます。
    - GPUを当分使う予定がない場合の例（期限を9999年12月31日に設定）
      onsei_register_desired_gpus 0 9999/12/31
    - 8枚確保したい場合の例（期限を2022年10月27日に設定し，コメントを付ける）
      onsei_register_desired_gpus 8 2022/10/27 '研究締切のためすみません'
    - 最低2枚確保し，研究室全体で余ったGPUも使いたい場合の例
      onsei_register_desired_gpus 2 2022/10/27 '余剰GPUを使わせていただきます'

USER      RUNNING DESIRED     TO DATE  COMMENT
============================================================================
hidaka          0       0  9999/12/31  自動コメント：2022/09/30に期限切れ
minami          8       4  2022/10/31  余剰GPUを使わせていただきます
takehisa        0       0  9999/12/31  自動コメント：2022/10/31に期限切れ
fujita          7       5  2022/10/31  使います
============================================================================
Remaining       1

Traceback (most recent call last):
  File "train_default.py", line 11, in <module>
    from librosa.display import specshow
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/__init__.py", line 211, in <module>
    from . import core
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/core/__init__.py", line 5, in <module>
    from .convert import *  # pylint: disable=wildcard-import
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/core/convert.py", line 7, in <module>
    from . import notation
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/core/notation.py", line 8, in <module>
    from ..util.exceptions import ParameterError
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/util/__init__.py", line 83, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/librosa/util/utils.py", line 10, in <module>
    import numba
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/numba/__init__.py", line 198, in <module>
    _ensure_critical_deps()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/numba/__init__.py", line 138, in _ensure_critical_deps
    raise ImportError("Numba needs NumPy 1.20 or less")
ImportError: Numba needs NumPy 1.20 or less
