2022-06-06 18:42:35,134 INFO    MainThread:142147 [wandb_setup.py:_flush():71] setting env: {}
2022-06-06 18:42:35,135 INFO    MainThread:142147 [wandb_setup.py:_flush():71] setting login settings: {}
2022-06-06 18:42:35,135 INFO    MainThread:142147 [wandb_init.py:_log_setup():371] Logging user logs to /home/usr1/q70261a/lip2sp_pytorch/wandb/run-20220606_184235-1omsxbj4/logs/debug.log
2022-06-06 18:42:35,136 INFO    MainThread:142147 [wandb_init.py:_log_setup():372] Logging internal logs to /home/usr1/q70261a/lip2sp_pytorch/wandb/run-20220606_184235-1omsxbj4/logs/debug-internal.log
2022-06-06 18:42:35,136 INFO    MainThread:142147 [wandb_init.py:init():404] calling init triggers
2022-06-06 18:42:35,136 INFO    MainThread:142147 [wandb_init.py:init():409] wandb.init called with sweep_config: {}
config: {}
2022-06-06 18:42:35,136 INFO    MainThread:142147 [wandb_init.py:init():460] starting backend
2022-06-06 18:42:35,136 INFO    MainThread:142147 [backend.py:_multiprocessing_setup():99] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-06-06 18:42:35,305 INFO    MainThread:142147 [backend.py:ensure_launched():216] starting backend process...
2022-06-06 18:42:35,357 INFO    MainThread:142147 [backend.py:ensure_launched():221] started backend process with pid: 142213
2022-06-06 18:42:35,358 INFO    MainThread:142147 [wandb_init.py:init():469] backend started and connected
2022-06-06 18:42:35,359 INFO    MainThread:142147 [wandb_init.py:init():533] updated telemetry
2022-06-06 18:42:35,454 INFO    MainThread:142147 [wandb_init.py:init():563] communicating current version
2022-06-06 18:42:37,032 INFO    MainThread:142147 [wandb_init.py:init():568] got version response upgrade_message: "wandb version 0.12.17 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2022-06-06 18:42:37,032 INFO    MainThread:142147 [wandb_init.py:init():578] communicating run to backend with 30 second timeout
2022-06-06 18:43:07,033 INFO    MainThread:142147 [interface_shared.py:_communicate_run():313] couldn't get run from backend
2022-06-06 18:43:07,034 ERROR   MainThread:142147 [wandb_init.py:init():583] backend process timed out
2022-06-06 18:43:07,034 ERROR   MainThread:142147 [wandb_init.py:init():592] encountered error: Error communicating with wandb process
try: wandb.init(settings=wandb.Settings(start_method='fork'))
or:  wandb.init(settings=wandb.Settings(start_method='thread'))
For more info see: https://docs.wandb.ai/library/init#init-start-error
2022-06-06 18:43:07,083 ERROR   MainThread:142147 [wandb_init.py:init():958] error
Traceback (most recent call last):
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 931, in init
    run = wi.init()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/wandb_init.py", line 596, in init
    backend.cleanup()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/backend/backend.py", line 245, in cleanup
    self.interface.join()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 458, in join
    super().join()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/interface/interface.py", line 599, in join
    _ = self._communicate_shutdown()
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 455, in _communicate_shutdown
    _ = self._communicate(record)
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/usr1/q70261a/.pyenv/versions/3.8.10/lib/python3.8/site-packages/wandb/sdk/interface/interface_shared.py", line 218, in _communicate_async
    raise Exception("The wandb backend process has shutdown")
Exception: The wandb backend process has shutdown
